[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
remappings = [
  "ds-test/=lib/ds-test/src/",
  "solmate/=lib/solmate/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src",
]
verbosity = 3
fs_permissions = [{ access = "read-write", path = "./"}]

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000


